/**
 * Exercise Database — Antigravity
 *
 * Structure: grouped object keyed by muscle group
 * Groups: chest | back | biceps | triceps | shoulders | abs | legs
 *
 * Per-exercise fields:
 *   id          {string}  Stable kebab-case ID, prefixed by group, zero-padded. e.g. "chest-001"
 *                         Unique across the entire library. Never reassigned once set.
 *   name        {string}  Display name in English. Title case.
 *   group       {string}  Must match the parent key exactly. e.g. "chest"
 *   description {string}  2–4 sentences. Action-focused how-to. No "you should" — direct imperative.
 *   videoId     {string}  YouTube video ID only (not full URL). e.g. "dQw4w9WgXcQ"
 *                         Thumbnail computed as: https://img.youtube.com/vi/${videoId}/hqdefault.jpg
 *                         Watch URL computed as: https://youtu.be/${videoId}
 *   svgKey      {string}  Key into svgIllustrations map. Spanish kebab-case. e.g. "press-pecho-plano"
 */

export const muscleGroups = ['chest', 'back', 'biceps', 'triceps', 'shoulders', 'abs', 'legs'];

export const exercises = {

  chest: [
    {
      id: "chest-001",
      name: "Flat Barbell Bench Press",
      group: "chest",
      description: "Lie flat on a bench, grip the bar slightly wider than shoulder-width, and unrack it over your chest. Lower the bar with control to mid-chest, touching lightly, then press it back up to full lockout. Keep your shoulder blades pinched together and feet flat on the floor throughout.",
      videoId: "hWbUlkb5Ms4",
      svgKey: "press-pecho-plano",
    },
    {
      id: "chest-002",
      name: "Incline Dumbbell Press",
      group: "chest",
      description: "Set a bench to 30–45 degrees, hold dumbbells at shoulder height, and press them overhead to full extension. Lower with control until your elbows are slightly below bench level for a full stretch. The incline angle shifts emphasis to the upper (clavicular) head of the pec.",
      videoId: "8fXfwG4ftaQ",
      svgKey: "press-inclinado-mancuernas",
    },
    {
      id: "chest-003",
      name: "Dumbbell Flat Fly",
      group: "chest",
      description: "Lie on a flat bench holding dumbbells above your chest with a slight bend in your elbows. Lower the weights in a wide arc until you feel a deep stretch across your chest, then squeeze them back together at the top. Maintain the same elbow angle throughout — this is not a pressing movement.",
      videoId: "rk8YayRoTRQ",
      svgKey: "aperturas-mancuernas",
    },
    {
      id: "chest-004",
      name: "Decline Dumbbell Press",
      group: "chest",
      description: "Set a bench to a 15–30 degree decline, secure your legs, and press dumbbells from shoulder height to full extension. The decline angle shifts emphasis to the lower chest fibers. Lower with control and feel the stretch at the bottom before driving back up.",
      videoId: "WbCEvFA0NJs",
      svgKey: "press-declinado-mancuernas",
    },
    {
      id: "chest-005",
      name: "Dumbbell Pullover",
      group: "chest",
      description: "Lie perpendicular across a bench with only your upper back supported, hold one dumbbell with both hands above your chest. Lower the dumbbell in an arc behind your head, feeling a deep stretch through your chest and lats. Pull it back to the starting position by contracting your chest.",
      videoId: "JdzaVp3zEAM",
      svgKey: "pullover-mancuerna",
    },
    {
      id: "chest-006",
      name: "Squeeze Press",
      group: "chest",
      description: "Lie on a flat bench holding dumbbells together at the center of your chest, pressing them firmly against each other. Press straight up while maintaining that inward squeeze to maximally activate the inner pec fibers. Lower slowly, keeping the dumbbells in contact throughout the movement.",
      videoId: "G2j_lJf6ljk",
      svgKey: "squeeze-press",
    },
    {
      id: "chest-007",
      name: "Machine Chest Press",
      group: "chest",
      description: "Sit in the chest press machine with your back flat against the pad and handles at chest level. Press forward to full arm extension, squeezing your chest at the lockout. Return slowly under control — the machine provides constant tension through the full range.",
      videoId: "Qu7-ceCvq7w",
      svgKey: "press-pecho-maquina",
    },
    {
      id: "chest-008",
      name: "Pec Deck Fly",
      group: "chest",
      description: "Sit in the pec deck machine with your forearms resting on the pads and elbows at shoulder height. Bring the pads together in front of you by squeezing your chest, then return slowly to the starting position. Avoid letting the weight stack touch between reps to maintain constant tension.",
      videoId: "fgXSA2-o0NM",
      svgKey: "pec-deck",
    },
    {
      id: "chest-009",
      name: "Incline Machine Press",
      group: "chest",
      description: "Adjust the incline chest press machine seat so the handles align with your upper chest. Press forward and slightly upward to full extension, then lower under control. The fixed path of the machine lets you focus entirely on contracting the upper chest.",
      videoId: "T0huVIujERo",
      svgKey: "press-inclinado-maquina",
    },
    {
      id: "chest-010",
      name: "Machine Crossover",
      group: "chest",
      description: "Stand between two cable towers set at shoulder height, hold the handles, and step forward. Bring both hands together in front of your chest in a hugging motion, squeezing hard at the peak contraction. Return slowly with control, feeling the stretch across your chest.",
      videoId: "y4RJDSOBEl8",
      svgKey: "crossover-maquina",
    },
    {
      id: "chest-011",
      name: "Smith Machine Bench Press",
      group: "chest",
      description: "Set up the Smith machine bar at chest height, lie on the bench and grip the bar slightly wider than shoulder-width. Lower the bar to mid-chest with control, then press back up to full extension. The fixed bar path lets you focus on chest activation without balancing concerns.",
      videoId: "gQ3afio08V8",
      svgKey: "smith-press-pecho",
    },
    {
      id: "chest-012",
      name: "Decline Machine Press",
      group: "chest",
      description: "Sit in the decline chest press machine and press the handles forward and slightly downward to full extension. This angle targets the lower chest fibers more directly than a flat press. Return slowly to feel the full eccentric stretch.",
      videoId: "RW4x8oAqPGQ",
      svgKey: "press-declinado-maquina",
    },
    {
      id: "chest-013",
      name: "Cable Crossover",
      group: "chest",
      description: "Stand between two cable towers set at the top, grab one handle in each hand, and step forward. Bring both hands together in a sweeping arc downward and inward, squeezing your chest hard at the bottom. Return to start slowly, maintaining tension on the chest throughout.",
      videoId: "M97ra0UR-40",
      svgKey: "crossover-cables",
    },
    {
      id: "chest-014",
      name: "Resistance Band Press",
      group: "chest",
      description: "Anchor a resistance band behind you at chest height, hold one end in each hand, and stand facing away. Press your hands forward to full extension, squeezing your chest at the lockout. Return under control, letting the band pull your arms back for an eccentric stretch.",
      videoId: "T0UJ0W-_yIE",
      svgKey: "press-bandas-pecho",
    },
    {
      id: "chest-015",
      name: "Low Cable Fly",
      group: "chest",
      description: "Set cables at the lowest point, stand between the towers, and bring both handles upward and inward in a sweeping arc to chest height. This angle targets the upper and mid chest with a strong stretch at the bottom. Squeeze hard at the peak and return slowly.",
      videoId: "tGXIQR89-JE",
      svgKey: "aperturas-cables-bajo",
    },
    {
      id: "chest-016",
      name: "High Cable Fly",
      group: "chest",
      description: "Set cables at the highest point, grab the handles and step forward. Bring both hands downward and inward in a sweeping arc, finishing with hands together at hip level. This targets the lower chest fibers with a powerful stretch at the top of the movement.",
      videoId: "I-Ue34qLxc4",
      svgKey: "aperturas-cables-alto",
    },
    {
      id: "chest-017",
      name: "Incline Cable Press",
      group: "chest",
      description: "Set a cable at the lowest setting, lie back on an incline bench, and press one or both handles upward at an incline angle to full extension. This isolates the upper chest with constant cable tension throughout the range of motion. Lower with control back to chest level.",
      videoId: "PfmfAeMpym4",
      svgKey: "press-inclinado-cable",
    },
    {
      id: "chest-018",
      name: "Single-Arm Cable Crossover",
      group: "chest",
      description: "Set a cable at shoulder height, grab the handle with one hand, and step away from the tower. Bring your arm across your body in a sweeping motion, finishing at hip level on the opposite side. This unilateral movement corrects imbalances and allows for a deeper pec stretch.",
      videoId: "E_mT1JWOp90",
      svgKey: "cruce-cable-unilateral",
    },
    {
      id: "chest-019",
      name: "Push-Up",
      group: "chest",
      description: "Start in a high plank position with hands slightly wider than shoulder-width and body in a straight line. Lower your chest to the floor by bending your elbows at roughly 45 degrees from your torso. Press back up to full arm extension while keeping your core tight and hips level throughout.",
      videoId: "IODxDxX7oi4",
      svgKey: "press-pecho-plano",
    },
    {
      id: "chest-020",
      name: "Wide-Grip Push-Up",
      group: "chest",
      description: "Take a push-up position with hands placed significantly wider than shoulder-width, fingers pointing outward. Lower your chest toward the floor, keeping your elbows flaring wide to maximize pec stretch. Press back up — the wide hand position shifts emphasis from the triceps to the outer chest fibers.",
      videoId: "i37y6EHOi8Q",
      svgKey: "press-pecho-plano",
    },
    {
      id: "chest-021",
      name: "Diamond Push-Up",
      group: "chest",
      description: "Form a diamond shape with your thumbs and index fingers beneath your chest and take a plank position. Lower your chest toward your hands, keeping your elbows close to your sides. Press back up — the narrow hand placement maximally loads the inner chest and triceps.",
      videoId: "J0DXyMHj7YA",
      svgKey: "press-pecho-plano",
    },
    {
      id: "chest-022",
      name: "Decline Push-Up",
      group: "chest",
      description: "Place your feet on a bench or elevated surface and your hands on the floor in a push-up position. Lower your chest toward the floor, then press back up. The elevated feet shift the angle to target the upper chest, similar to an incline press but using bodyweight.",
      videoId: "SKPab2YC8BE",
      svgKey: "press-inclinado-maquina",
    },
    {
      id: "chest-023",
      name: "Incline Barbell Bench Press",
      group: "chest",
      description: "Set a bench to 30-45 degrees, lie back and grip the bar slightly wider than shoulder-width. Unrack the bar and lower it to your upper chest with control, then press back up to full extension. The incline shifts emphasis to the clavicular (upper) head of the pectoralis major.",
      videoId: "jPLdzuHckI8",
      svgKey: "press-inclinado-mancuernas",
    },
    {
      id: "chest-024",
      name: "Decline Barbell Bench Press",
      group: "chest",
      description: "Set a bench to a 15-30 degree decline and secure your feet. Grip the bar slightly wider than shoulder-width, unrack it over your lower chest, and lower with control. Press back up to full extension — the decline angle targets the lower pectoral fibers more directly than a flat press.",
      videoId: "HGd0DmOBsKU",
      svgKey: "press-declinado-mancuernas",
    },
    {
      id: "chest-025",
      name: "Incline Dumbbell Fly",
      group: "chest",
      description: "Set a bench to 30-45 degrees, hold dumbbells above your upper chest with a slight elbow bend. Lower the weights in a wide arc until you feel a deep stretch in your upper chest, then sweep them back together. Keep the same elbow bend throughout — this is a fly, not a press.",
      videoId: "jR0Ey_m9T0Y",
      svgKey: "press-inclinado-mancuernas",
    },
    {
      id: "chest-026",
      name: "Cable Fly (Mid)",
      group: "chest",
      description: "Set both cables at mid-chest height and stand centered between the towers with one foot forward. Bring both handles together in front of your chest in a hugging arc, squeezing hard at the peak. Return slowly — mid-height cables target the sternal (mid) chest with constant tension throughout.",
      videoId: "w0KWaLRTl6Y",
      svgKey: "crossover-cables",
    },
    {
      id: "chest-027",
      name: "Smith Machine Incline Press",
      group: "chest",
      description: "Set an incline bench inside a Smith machine, adjust the bar to just above your upper chest, and grip slightly wider than shoulder-width. Press the bar straight up to full extension, then lower with control. The fixed bar path lets you focus on upper chest activation without stabilizer fatigue.",
      videoId: "W6NFQInKPzY",
      svgKey: "smith-press-pecho",
    },
    {
      id: "chest-028",
      name: "Chest Dip",
      group: "chest",
      description: "Grip parallel bars and lean your torso forward at a 30-45 degree angle throughout the movement. Lower yourself by bending your elbows until your upper arms are parallel to the floor, feeling a stretch across your chest. Press back up to full extension — leaning forward shifts the load from triceps to the lower chest.",
      videoId: "sM8LyoHOs54",
      svgKey: "dip-asistido",
    },
    {
      id: "chest-029",
      name: "Resistance Band Fly",
      group: "chest",
      description: "Anchor a resistance band behind you at chest height and hold one end in each hand with arms wide. Bring both hands together in front of your chest in a sweeping fly motion, squeezing hard at the peak. Return slowly against the band tension — bands provide increasing resistance at peak pec contraction.",
      videoId: "3FJKBrFRu1k",
      svgKey: "press-bandas-pecho",
    },
    {
      id: "chest-030",
      name: "Svend Press",
      group: "chest",
      description: "Hold two weight plates pressed together at chest level with both palms flat against the plates. Press the plates straight out to full arm extension while maintaining inward pressing force between them. Pull them back to your chest slowly — the constant squeeze activates the inner pec fibers throughout the movement.",
      videoId: "v-AMqYhbzno",
      svgKey: "squeeze-press",
    },
  ],

  back: [
    {
      id: "back-001",
      name: "Barbell Bent-Over Row",
      group: "back",
      description: "Hinge at the hips until your torso is roughly parallel to the floor, keeping your lower back flat. Pull the bar into your lower abdomen by driving your elbows back and squeezing your shoulder blades together. Lower with control and avoid using momentum from your legs.",
      videoId: "UL8ZcK64KxA",
      svgKey: "remo-inclinado-bilateral",
    },
    {
      id: "back-002",
      name: "Pull-Up",
      group: "back",
      description: "Hang from a bar with an overhand grip slightly wider than shoulder-width. Pull yourself up until your chin clears the bar by driving your elbows down toward your hips. Lower slowly under control — the descent is where much of the back development happens.",
      videoId: "OEXosPwzFdc",
      svgKey: "jalon-pecho",
    },
    {
      id: "back-003",
      name: "Lat Pulldown",
      group: "back",
      description: "Sit at a cable machine with your thighs secured under the pad and grip the bar slightly wider than shoulder-width. Pull the bar down to your upper chest by driving your elbows toward your hips while leaning back slightly. Squeeze your lats at the bottom and return the bar slowly to full arm extension.",
      videoId: "SALxEARiMkw",
      svgKey: "jalon-pecho",
    },
    {
      id: "back-004",
      name: "Dumbbell Row",
      group: "back",
      description: "Place one knee and hand on a bench for support, hold a dumbbell in the other hand, and let it hang straight down. Row the dumbbell up to your hip by driving your elbow back, squeezing your shoulder blade at the top. Lower fully to feel the lat stretch before each rep.",
      videoId: "qN54-QNO1eQ",
      svgKey: "remo-mancuerna",
    },
    {
      id: "back-005",
      name: "Dumbbell Deadlift",
      group: "back",
      description: "Stand with dumbbells in front of your thighs, hinge at the hips while keeping your back flat, and lower them toward the floor. Drive your hips forward to return to standing, squeezing your glutes at the top. Keep the dumbbells close to your legs throughout the movement.",
      videoId: "Ipi8_vz8_z0",
      svgKey: "peso-muerto-mancuernas",
    },
    {
      id: "back-006",
      name: "Pullover (Back Focus)",
      group: "back",
      description: "Lie on a bench holding a dumbbell with both hands overhead. Lower it in an arc behind your head until you feel a strong lat stretch, then pull it back overhead by contracting your lats and serratus. Keep a slight elbow bend throughout and focus on the lat contraction, not the chest.",
      videoId: "Datv2L6t3-4",
      svgKey: "pullover-espalda",
    },
    {
      id: "back-007",
      name: "Kroc Row",
      group: "back",
      description: "Set up like a standard dumbbell row but use a heavier weight with a controlled touch of momentum. Pull the dumbbell aggressively to your hip, focusing on maximum lat contraction at the top. Lower with control — this high-rep, heavier variant builds raw back thickness.",
      videoId: "bX-LZ5nBLBk",
      svgKey: "remo-kroc",
    },
    {
      id: "back-008",
      name: "Dumbbell Shrug",
      group: "back",
      description: "Stand holding dumbbells at your sides with arms fully extended. Elevate your shoulders straight up toward your ears as high as possible, hold briefly at the top, then lower slowly. Do not roll your shoulders — the movement is purely vertical to target the upper traps.",
      videoId: "rFsSeClGnNA",
      svgKey: "encogimientos-mancuernas",
    },
    {
      id: "back-009",
      name: "Seated Cable Row",
      group: "back",
      description: "Sit at a cable row machine with feet on the footplate and knees slightly bent. Pull the handle into your lower abdomen by driving your elbows back and squeezing your shoulder blades together. Return to full arm extension with a slight forward lean to stretch your lats between reps.",
      videoId: "vwHG9Jfu4sw",
      svgKey: "remo-sentado-maquina",
    },
    {
      id: "back-010",
      name: "Close-Grip Lat Pulldown",
      group: "back",
      description: "Attach a close-grip or V-bar handle to the cable machine and sit with thighs under the pad. Pull the handle down to your upper chest, driving your elbows toward your sides and squeezing your lats hard at the bottom. The narrow grip increases bicep involvement and shifts lat activation lower.",
      videoId: "e3S820r53uk",
      svgKey: "jalon-agarre-cerrado",
    },
    {
      id: "back-011",
      name: "T-Bar Row",
      group: "back",
      description: "Straddle a T-bar or landmine setup, hinge forward with a flat back, and grip the handles. Row the weight up to your lower chest by driving your elbows back, squeezing your shoulder blades together at the top. Lower with control — this is a powerful compound movement for mid-back thickness.",
      videoId: "TyLoy3n_a10",
      svgKey: "remo-tbar",
    },
    {
      id: "back-012",
      name: "Straight-Arm Pulldown",
      group: "back",
      description: "Stand at a cable machine with the bar set high, grab it with an overhand grip and arms extended. Keep your arms straight and pull the bar down in an arc until it reaches your thighs, squeezing your lats hard at the bottom. Return slowly — this isolates the lats without bicep involvement.",
      videoId: "hAMcfubonDc",
      svgKey: "pulldown-brazos-rectos",
    },
    {
      id: "back-013",
      name: "Hyperextension",
      group: "back",
      description: "Position yourself face-down on a hyperextension bench with your hips on the pad and feet secured. Lower your torso toward the floor, then raise it back to parallel by contracting your lower back and glutes. Keep your spine neutral — do not hyperextend beyond parallel at the top.",
      videoId: "EBui4Bt5N7o",
      svgKey: "hiperextension",
    },
    {
      id: "back-014",
      name: "Cable Row (Standing)",
      group: "back",
      description: "Stand at a cable machine with the pulley set at mid-height and grip the handle with one or both hands. Pull the handle into your torso by driving your elbow back, squeezing your shoulder blade at the end range. Step back slightly against the cable tension to maintain constant resistance.",
      videoId: "hh-8Igj6wuo",
      svgKey: "remo-cable",
    },
    {
      id: "back-015",
      name: "Band Face Pull",
      group: "back",
      description: "Anchor a resistance band at face height, hold an end in each hand, and step back to create tension. Pull the band toward your face by driving your elbows back and out, finishing with your hands beside your ears. This targets the rear delts and upper traps while improving shoulder health.",
      videoId: "Qij3pSB-gNk",
      svgKey: "face-pull",
    },
    {
      id: "back-016",
      name: "Band Lat Pulldown",
      group: "back",
      description: "Anchor a resistance band overhead and kneel or sit below it. Grab the band with both hands and pull it down to your upper chest by driving your elbows toward your hips. Return slowly to full arm extension — bands provide greater resistance at the top and a strong lat stretch at full extension.",
      videoId: "nmY4MTSFln8",
      svgKey: "jalon-banda",
    },
    {
      id: "back-017",
      name: "Low Cable Row",
      group: "back",
      description: "Sit on a cable machine with the pulley set at the lowest position and a straight bar or rope attached. Pull the handle into your lower abdomen with a slight forward lean at the start, then drive your elbows back and sit tall. This angle builds lower lat fullness and overall back thickness.",
      videoId: "QelgBRgIsjY",
      svgKey: "remo-bajo-cable",
    },
    {
      id: "back-018",
      name: "Cable Pullover",
      group: "back",
      description: "Stand at a cable machine with the pulley overhead, grip the bar or rope with both hands and arms extended. Pull the bar down in an arc to your thighs while keeping your arms straight, squeezing your lats at the bottom. This is the cable version of a pullover — constant tension through the full range.",
      videoId: "MeczZ6iUYPo",
      svgKey: "pullover-cable",
    },
    {
      id: "back-019",
      name: "Chin-Up",
      group: "back",
      description: "Hang from a bar with an underhand (supinated) grip at shoulder-width. Pull yourself up until your chin clears the bar, driving your elbows toward your hips. Lower slowly under full control — the supinated grip increases bicep contribution and shifts lat activation toward the lower fibers.",
      videoId: "1M_KRPQ_Kbs",
      svgKey: "jalon-pecho",
    },
    {
      id: "back-020",
      name: "Wide-Grip Pull-Up",
      group: "back",
      description: "Hang from a bar with an overhand grip significantly wider than shoulder-width. Pull yourself up until your chin clears the bar, focusing on driving your elbows down and out. Lower with full control — the wide grip increases the range of lat activation and builds width.",
      videoId: "eGo4IYlbE5g",
      svgKey: "jalon-pecho",
    },
    {
      id: "back-021",
      name: "Barbell Deadlift",
      group: "back",
      description: "Stand over a loaded barbell with feet hip-width apart, grip just outside your legs, and hinge down while keeping your back flat. Drive through your heels and extend your hips and knees simultaneously to lift the bar. Lock out at the top by squeezing your glutes — then lower with control.",
      videoId: "r4MzxtBKyNE",
      svgKey: "peso-muerto-mancuernas",
    },
    {
      id: "back-022",
      name: "Sumo Deadlift",
      group: "back",
      description: "Take a very wide stance with toes pointed out, grip the bar with hands inside your knees. Drive your knees out and hips forward as you lift, keeping the bar close to your body. The sumo stance reduces lower back load while increasing hip and inner thigh involvement.",
      videoId: "Cf4SBdJbXFY",
      svgKey: "peso-muerto-mancuernas",
    },
    {
      id: "back-023",
      name: "Pendlay Row",
      group: "back",
      description: "Set up like a barbell row but start each rep from a dead stop on the floor. Hinge to a horizontal torso position, then explosively row the bar to your lower chest. Lower the bar all the way back to the floor between each rep — the dead stop eliminates momentum and forces maximum lat recruitment.",
      videoId: "Hm4MebTbVVQ",
      svgKey: "remo-inclinado-bilateral",
    },
    {
      id: "back-024",
      name: "Meadows Row",
      group: "back",
      description: "Place a barbell in a landmine or corner, stand perpendicular to it, and grip the far end with one hand. Row the bar up to your hip in a sweeping arc, driving your elbow back and high. Lower with control — this angle targets the upper lat and teres major with a unique pull direction.",
      videoId: "ZBMEVZDJbMY",
      svgKey: "remo-kroc",
    },
    {
      id: "back-025",
      name: "Machine Row",
      group: "back",
      description: "Sit in the chest-supported row machine with your chest against the pad. Pull the handles toward your torso by driving your elbows back, squeezing your shoulder blades together at the end range. Return to full arm extension — the chest support eliminates lower back strain for strict back isolation.",
      videoId: "7LfpKkHVhic",
      svgKey: "remo-sentado-maquina",
    },
    {
      id: "back-026",
      name: "High Cable Row",
      group: "back",
      description: "Sit at a cable machine with the pulley set above head height and pull the bar or rope down to your upper chest. Drive your elbows back and down, squeezing your upper back and rear delts at the end range. Return with full arm extension — this high-angle row targets the upper back and rhomboids.",
      videoId: "gKPl-Nf5HnU",
      svgKey: "remo-alto-cable",
    },
    {
      id: "back-027",
      name: "Single-Arm Cable Row",
      group: "back",
      description: "Sit at a cable station with the pulley at low height and pull one handle with one hand. Drive your elbow back past your torso, rotating your shoulder slightly for full contraction. Return to full extension — the unilateral movement allows greater range and corrects left-right imbalances.",
      videoId: "TWTMXiMGKaU",
      svgKey: "remo-cable",
    },
    {
      id: "back-028",
      name: "Rack Pull",
      group: "back",
      description: "Set a barbell in a power rack at knee height, grip it with an overhand or mixed grip at shoulder-width. Pull the bar up by driving your hips forward and extending your back to full lockout. Lower back to the pins — the shortened range allows heavier loading and emphasizes upper back and trap strength.",
      videoId: "P1_J4_PvSlg",
      svgKey: "hiperextension",
    },
    {
      id: "back-029",
      name: "Jefferson Curl",
      group: "back",
      description: "Stand on a box or step holding a light barbell or dumbbells, and slowly roll your spine down vertebra by vertebra toward the floor. Allow your spine to fully flex and feel a deep stretch through your entire back and hamstrings. Roll back up from the base of the spine — this is a mobility and strength exercise, not a power movement.",
      videoId: "5_e6xJGNmOU",
      svgKey: "hiperextension",
    },
    {
      id: "back-030",
      name: "Chest-Supported T-Bar Row",
      group: "back",
      description: "Lie face-down on an incline bench over a T-bar or landmine setup and grip the handles below your chest. Row the weight up by driving your elbows back and squeezing your shoulder blades hard at the top. Lower to full arm extension — the chest support eliminates all lower back involvement for pure back training.",
      videoId: "j7yOqpqQMEc",
      svgKey: "remo-tbar",
    },
  ],

  biceps: [
    {
      id: "biceps-001",
      name: "Barbell Curl",
      group: "biceps",
      description: "Stand holding a barbell with an underhand grip at shoulder width, arms fully extended. Curl the bar up toward your shoulders by contracting your biceps, keeping your elbows pinned to your sides. Lower the bar slowly back to full extension — do not swing your torso.",
      videoId: "ez3YoWf62Eg",
      svgKey: "curl-biceps",
    },
    {
      id: "biceps-002",
      name: "Dumbbell Hammer Curl",
      group: "biceps",
      description: "Hold dumbbells at your sides with a neutral (palms-facing-in) grip. Curl both dumbbells simultaneously up toward your shoulders without rotating your wrists. This neutral grip targets the brachialis and brachioradialis alongside the biceps for overall arm thickness.",
      videoId: "BRVDS6HVR9Q",
      svgKey: "curl-martillo",
    },
    {
      id: "biceps-003",
      name: "Incline Dumbbell Curl",
      group: "biceps",
      description: "Set a bench to 60–70 degrees, sit back against it, and let your arms hang straight down. Curl the dumbbells up while keeping your upper arms stationary and perpendicular to the floor throughout. The incline position pre-stretches the long head of the biceps for a greater range of motion.",
      videoId: "XhIsIcjIbCw",
      svgKey: "curl-concentrado",
    },
    {
      id: "biceps-004",
      name: "Zottman Curl",
      group: "biceps",
      description: "Curl dumbbells up with an underhand (supinated) grip, rotating your wrists to an overhand (pronated) grip at the top. Lower slowly with the overhand grip to work the brachioradialis and forearm extensors eccentrically. Rotate back to underhand at the bottom before the next rep.",
      videoId: "D7bMA4WEKMI",
      svgKey: "curl-zottman",
    },
    {
      id: "biceps-005",
      name: "Biceps Machine Curl",
      group: "biceps",
      description: "Sit in the biceps curl machine with your upper arms resting on the pad and elbows aligned with the pivot point. Curl the handles up to full contraction, squeezing your biceps hard at the top. Lower slowly to full extension — the pad isolates the biceps by preventing shoulder involvement.",
      videoId: "Htw-s61mOw0",
      svgKey: "curl-maquina-biceps",
    },
    {
      id: "biceps-006",
      name: "Overhead Triceps Extension",
      group: "biceps",
      description: "Hold a dumbbell with both hands overhead at full arm extension. Lower it behind your head by bending at the elbows, keeping your upper arms vertical. Press back up to full extension — the overhead position stretches the long head maximally for full triceps development.",
      videoId: "eYrAV7rnol0",
      svgKey: "extension-triceps-overhead",
    },
    {
      id: "biceps-007",
      name: "Preacher Machine Curl",
      group: "biceps",
      description: "Sit at the preacher curl machine with your upper arms resting flat on the angled pad. Curl the handles up to full contraction, squeezing your biceps at the top. Lower with full control to complete extension — the pad eliminates cheating and puts maximum stress on the biceps peak.",
      videoId: "OI6gZcAPUMU",
      svgKey: "curl-predicador-maquina",
    },
    {
      id: "biceps-008",
      name: "Triceps Kickback",
      group: "biceps",
      description: "Hinge forward until your torso is nearly parallel to the floor, hold a dumbbell with your upper arm pinned to your side and elbow bent at 90 degrees. Extend your forearm back to full lockout, squeezing the triceps hard at the top. Lower with control — do not let your upper arm drop.",
      videoId: "I_bKCYL2nL8",
      svgKey: "kickback-triceps",
    },
    {
      id: "biceps-009",
      name: "Scott Machine Curl",
      group: "biceps",
      description: "Position yourself in the Scott curl machine with your upper arms resting on the angled pad. Curl the bar or handles up toward your shoulders, squeezing your biceps at the top contraction. Lower with full control to a stretched position — the Scott bench prevents any shoulder cheating.",
      videoId: "NFzTWp2qpiE",
      svgKey: "curl-scott-maquina",
    },
    {
      id: "biceps-010",
      name: "Triceps Machine Extension",
      group: "biceps",
      description: "Sit in the triceps extension machine with your upper arms resting on the pads. Push the handles down to full lockout by extending your elbows, squeezing your triceps hard at the bottom. Return slowly — the machine provides consistent resistance through the full range of motion.",
      videoId: "20xtfGZ37nw",
      svgKey: "extension-triceps-maquina",
    },
    {
      id: "biceps-011",
      name: "French Press Machine",
      group: "biceps",
      description: "Lie on the bench of the French press machine and grip the handles above your forehead. Lower toward your forehead by bending at the elbows, then press back up to full extension. This compound movement is ideal for loading the long head of the triceps at a full overhead stretch.",
      videoId: "IJZhj9szYcw",
      svgKey: "press-frances-maquina",
    },
    {
      id: "biceps-012",
      name: "Cable Curl",
      group: "biceps",
      description: "Stand at a cable machine with the pulley set low and grip the bar or rope with an underhand grip. Curl upward toward your shoulders, keeping your elbows stationary at your sides. Lower slowly — cables provide constant tension throughout the full range, unlike free weights.",
      videoId: "yz2eCSWoY4E",
      svgKey: "curl-cable",
    },
    {
      id: "biceps-013",
      name: "Triceps Pushdown",
      group: "biceps",
      description: "Stand at a cable machine with a rope or bar attached to the high pulley. Keeping your upper arms pinned to your sides, push the attachment down to full elbow extension. Squeeze your triceps at the bottom before returning slowly to the starting position.",
      videoId: "qmQkt1Y-FX8",
      svgKey: "pushdown-triceps",
    },
    {
      id: "biceps-014",
      name: "Band Curl",
      group: "biceps",
      description: "Stand on a resistance band with feet shoulder-width apart and hold one end in each hand. Curl both hands up toward your shoulders, squeezing your biceps at the top. Lower slowly — bands provide increasing resistance as you approach peak contraction, creating a unique strength curve.",
      videoId: "jgmESOA4J5E",
      svgKey: "curl-banda",
    },
    {
      id: "biceps-015",
      name: "Band Overhead Extension",
      group: "biceps",
      description: "Anchor a resistance band at a low point, hold the other end with both hands overhead at full arm extension. Lower the band behind your head by bending at the elbows, then press back up to full extension. This overhead position maximally stretches the long head of the triceps.",
      videoId: "16zAqGDsMI0",
      svgKey: "extension-banda-overhead",
    },
    {
      id: "biceps-016",
      name: "Reverse Cable Curl",
      group: "biceps",
      description: "Stand at a cable machine with the pulley set low and grip the bar with an overhand (pronated) grip. Curl upward toward your shoulders, keeping your elbows pinned to your sides throughout. This pronated grip shifts emphasis to the brachioradialis and forearm extensors.",
      videoId: "YC9QZiti-40",
      svgKey: "curl-inverso-polea",
    },
    {
      id: "biceps-017",
      name: "Band Triceps Extension",
      group: "biceps",
      description: "Anchor a resistance band overhead and grip it with both hands behind your head. Extend your forearms upward to full lockout, squeezing your triceps hard at the top. Return slowly — bands add resistance at the lockout position where triceps are strongest.",
      videoId: "FHY_2t7R714",
      svgKey: "extension-triceps-banda",
    },
    {
      id: "biceps-018",
      name: "Assisted Dip",
      group: "biceps",
      description: "Use the assisted dip machine to set your counterweight, grip the handles, and lower your body until your upper arms are parallel to the floor. Press back up to full lockout by extending your elbows, squeezing your triceps at the top. Progressively reduce assistance as your strength improves.",
      videoId: "2LpuygMBn4Q",
      svgKey: "dip-asistido",
    },
    {
      id: "biceps-019",
      name: "EZ Bar Curl",
      group: "biceps",
      description: "Hold an EZ bar at the angled inner grip with an underhand grip and arms fully extended. Curl the bar up toward your shoulders by contracting your biceps, keeping your elbows stationary at your sides. Lower slowly to full extension — the angled grip reduces wrist strain while maintaining effective bicep tension.",
      videoId: "zG2i0kxCPcc",
      svgKey: "curl-biceps",
    },
    {
      id: "biceps-020",
      name: "Wide-Grip Barbell Curl",
      group: "biceps",
      description: "Hold a barbell with an underhand grip wider than shoulder-width and arms fully extended. Curl the bar up toward your shoulders, keeping your elbows stationary. Lower slowly to full extension — the wide grip shifts emphasis to the short (inner) head of the biceps.",
      videoId: "ZrGJt5HBrHo",
      svgKey: "curl-biceps",
    },
    {
      id: "biceps-021",
      name: "Narrow-Grip Barbell Curl",
      group: "biceps",
      description: "Hold a barbell with your hands closer than shoulder-width, underhand grip, and curl up to full contraction. The narrow grip shifts emphasis to the long head (outer) of the biceps, helping develop the peak. Lower with full control and avoid swinging your torso.",
      videoId: "QlgouVCRIbY",
      svgKey: "curl-biceps",
    },
    {
      id: "biceps-022",
      name: "Cross-Body Hammer Curl",
      group: "biceps",
      description: "Hold dumbbells at your sides with a neutral grip. Curl one dumbbell across your body toward the opposite shoulder instead of straight up, then lower and alternate sides. This cross-body path targets the brachialis and the long head of the biceps at a unique angle.",
      videoId: "J6o5sOmh6a4",
      svgKey: "curl-martillo",
    },
    {
      id: "biceps-023",
      name: "Spider Curl",
      group: "biceps",
      description: "Lie face-down on an incline bench set to about 45 degrees and let your arms hang vertically. Curl dumbbells or a barbell up toward your face, keeping your upper arms perpendicular to the floor. Lower with full control — this position eliminates shoulder involvement and maximizes bicep tension throughout the range.",
      videoId: "pO8N6B5rhbU",
      svgKey: "curl-concentrado",
    },
    {
      id: "biceps-024",
      name: "Preacher Curl (Barbell)",
      group: "biceps",
      description: "Sit at a preacher bench and rest your upper arms flat on the angled pad. Hold a barbell with an underhand grip and curl up to full contraction, squeezing hard at the top. Lower slowly to full extension — the preacher angle prevents cheating and places peak tension on the lower bicep.",
      videoId: "fIWP-FRFNU0",
      svgKey: "curl-predicador-maquina",
    },
    {
      id: "biceps-025",
      name: "Prone Incline Dumbbell Curl",
      group: "biceps",
      description: "Set a bench to a low incline and lie face-down with your chest against the pad and arms hanging. Curl both dumbbells up toward your face simultaneously, keeping your upper arms still. Lower with full control — this position pre-stretches the biceps and prevents momentum from the shoulders.",
      videoId: "OjGbnJXMT7s",
      svgKey: "curl-concentrado",
    },
    {
      id: "biceps-026",
      name: "Rope Hammer Curl",
      group: "biceps",
      description: "Attach a rope to the low cable pulley and grip each end with a neutral (palms-in) grip. Curl your hands up toward your shoulders while maintaining the neutral grip throughout. Lower slowly — the rope allows each hand to move independently and the neutral position maximally loads the brachialis.",
      videoId: "wR-jWVnZeWo",
      svgKey: "curl-cable",
    },
    {
      id: "biceps-027",
      name: "High Cable Curl",
      group: "biceps",
      description: "Set both cables high on a cable crossover machine and grip the handles with underhand grip, arms extended. Curl both handles toward your ears simultaneously, squeezing your biceps at peak contraction. Lower with control — the high angle keeps constant tension on the biceps and mimics a most-muscular pose.",
      videoId: "V8dZ3pyiCBo",
      svgKey: "curl-cable",
    },
    {
      id: "biceps-028",
      name: "Alternating Dumbbell Curl",
      group: "biceps",
      description: "Stand holding dumbbells at your sides. Curl one arm up to full contraction while supinating your wrist at the top, then lower and repeat on the other side. Alternating allows a brief rest for each arm and lets you focus on full supination — the key to maximizing bicep peak contraction.",
      videoId: "sAq_ocpRh_I",
      svgKey: "curl-biceps",
    },
    {
      id: "biceps-029",
      name: "Reverse Barbell Curl",
      group: "biceps",
      description: "Hold a barbell with an overhand (pronated) grip at shoulder-width and curl up toward your shoulders. Keep your elbows stationary and lower with full control. The pronated grip removes supination and directly targets the brachioradialis and forearm extensors — critical for balanced arm development.",
      videoId: "nwZO5N6EOPY",
      svgKey: "curl-inverso-polea",
    },
    {
      id: "biceps-030",
      name: "21s Curl",
      group: "biceps",
      description: "Using a barbell, perform 7 reps from the bottom to mid-range (parallel), then 7 reps from mid-range to the top, then 7 full-range reps for 21 total reps. Each partial range intensifies the time-under-tension on different portions of the strength curve. Use a lighter weight than your normal curl — this protocol is brutally effective.",
      videoId: "x5fhIpHO_H8",
      svgKey: "curl-biceps",
    },
  ],

  triceps: [
    {
      id: "triceps-001",
      name: "Triceps Rope Pushdown",
      group: "triceps",
      description: "Stand at a cable machine with the rope attached to the high pulley. Keeping your upper arms pinned to your sides, push the rope down and apart until your arms are fully extended. Squeeze your triceps hard at the bottom before slowly returning to the start position.",
      videoId: "NvZKjiZ8NYc",
      svgKey: "pushdown-triceps",
    },
    {
      id: "triceps-002",
      name: "Overhead Triceps Extension (Dumbbell)",
      group: "triceps",
      description: "Hold one dumbbell with both hands and raise it overhead to full extension. Lower the dumbbell behind your head by bending at the elbows, keeping your upper arms vertical and close to your ears. Press back up to full extension — this overhead position maximally stretches the long head of the triceps.",
      videoId: "b_r_LW4HEcM",
      svgKey: "extension-triceps-overhead",
    },
    {
      id: "triceps-003",
      name: "Close-Grip Bench Press",
      group: "triceps",
      description: "Lie flat on a bench and grip the bar with your hands shoulder-width apart or slightly narrower. Lower the bar to your lower chest while keeping your elbows close to your torso at roughly 45 degrees. Press back up to lockout — the narrow grip shifts the load from the pecs to the triceps.",
      videoId: "vEUyEOVn3yM",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-004",
      name: "Barbell Curl",
      group: "triceps",
      description: "Stand holding a barbell with an underhand grip at shoulder width, arms fully extended. Curl the bar up toward your shoulders by contracting your biceps, keeping your elbows pinned to your sides. Lower the bar slowly back to full extension — do not swing your torso.",
      videoId: "zR9gty7LUxE",
      svgKey: "curl-biceps",
    },
    {
      id: "triceps-005",
      name: "Hammer Curl",
      group: "triceps",
      description: "Hold dumbbells at your sides with a neutral (palms-facing-in) grip. Curl both dumbbells simultaneously up toward your shoulders without rotating your wrists. This neutral grip targets the brachialis and brachioradialis alongside the biceps for overall arm thickness.",
      videoId: "3Bv1n7-DN7c",
      svgKey: "curl-martillo",
    },
    {
      id: "triceps-006",
      name: "Concentration Curl",
      group: "triceps",
      description: "Sit on a bench, lean forward slightly, and rest your upper arm against the inside of your thigh for support. Curl the dumbbell up toward your shoulder with full supination, squeezing hard at the top. Lower completely to full extension to maximize the range of motion.",
      videoId: "Cr3KukvJh2Y",
      svgKey: "curl-concentrado",
    },
    {
      id: "triceps-007",
      name: "Zottman Curl",
      group: "triceps",
      description: "Curl dumbbells up with an underhand grip, rotating your wrists to an overhand grip at the top. Lower slowly with the overhand grip to work the brachioradialis and forearm extensors eccentrically. Rotate back to underhand at the bottom before the next rep.",
      videoId: "9Ark9S11uXw",
      svgKey: "curl-zottman",
    },
    {
      id: "triceps-008",
      name: "Biceps Machine Curl",
      group: "triceps",
      description: "Sit in the biceps curl machine with your upper arms resting on the pad and elbows aligned with the pivot. Curl the handles up to full contraction, squeezing your biceps hard at the top. Lower slowly to full extension — the pad prevents shoulder involvement and isolates the biceps.",
      videoId: "4ua3MzaU0QU",
      svgKey: "curl-maquina-biceps",
    },
    {
      id: "triceps-009",
      name: "Preacher Machine Curl",
      group: "triceps",
      description: "Sit at the preacher curl machine with upper arms flat on the angled pad. Curl the handles up to full contraction, then lower with full control to complete extension. The pad eliminates cheating and places maximum tension on the biceps peak.",
      videoId: "v2wPD8fryIc",
      svgKey: "curl-predicador-maquina",
    },
    {
      id: "triceps-010",
      name: "Triceps Kickback",
      group: "triceps",
      description: "Hinge forward until your torso is nearly parallel to the floor, hold a dumbbell with your upper arm pinned to your side and elbow at 90 degrees. Extend your forearm back to full lockout, squeezing the triceps hard at the top. Lower with control — keep your upper arm stationary throughout.",
      videoId: "7lYeoKRXO-0",
      svgKey: "kickback-triceps",
    },
    {
      id: "triceps-011",
      name: "Scott Machine Curl",
      group: "triceps",
      description: "Position yourself at the Scott curl machine with upper arms resting on the angled pad. Curl the bar up to a peak contraction, squeezing hard, then lower with full control to a stretched position. The Scott bench prevents any shoulder cheating for strict biceps isolation.",
      videoId: "PtHlGbiCglY",
      svgKey: "curl-scott-maquina",
    },
    {
      id: "triceps-012",
      name: "Triceps Machine Extension",
      group: "triceps",
      description: "Sit in the triceps extension machine with upper arms resting on the pads. Push the handles down to full lockout, squeezing your triceps hard at the bottom. Return slowly — the machine provides consistent resistance through the full range of motion.",
      videoId: "8IK6BkC0lWE",
      svgKey: "extension-triceps-maquina",
    },
    {
      id: "triceps-013",
      name: "Cable Curl",
      group: "triceps",
      description: "Stand at a cable machine with the pulley set low and grip the bar with an underhand grip. Curl upward toward your shoulders, keeping your elbows stationary at your sides. Lower slowly — cables provide constant tension throughout the full range unlike free weights.",
      videoId: "7_C9_SWHZbo",
      svgKey: "curl-cable",
    },
    {
      id: "triceps-014",
      name: "Band Curl",
      group: "triceps",
      description: "Stand on a resistance band and hold one end in each hand. Curl both hands up toward your shoulders, squeezing your biceps at the top. Lower slowly — bands provide increasing resistance as you approach peak contraction.",
      videoId: "LH9iZNaO7oU",
      svgKey: "curl-banda",
    },
    {
      id: "triceps-015",
      name: "Band Overhead Extension",
      group: "triceps",
      description: "Anchor a resistance band low and hold the other end overhead with both hands at full arm extension. Lower the band behind your head by bending at the elbows, then press back up to full extension. This overhead position maximally stretches the long head of the triceps.",
      videoId: "YEdjByGD_A4",
      svgKey: "extension-banda-overhead",
    },
    {
      id: "triceps-016",
      name: "Reverse Cable Curl",
      group: "triceps",
      description: "Stand at a cable machine with the pulley low and grip the bar with an overhand (pronated) grip. Curl upward toward your shoulders, keeping your elbows pinned to your sides. This pronated grip shifts emphasis to the brachioradialis and forearm extensors.",
      videoId: "WhBxKbe1-NU",
      svgKey: "curl-inverso-polea",
    },
    {
      id: "triceps-017",
      name: "Band Triceps Extension",
      group: "triceps",
      description: "Anchor a resistance band overhead and grip it with both hands behind your head. Extend your forearms upward to full lockout, squeezing your triceps hard at the top. Return slowly to the start with control.",
      videoId: "cNNTAQcQa7I",
      svgKey: "extension-triceps-banda",
    },
    {
      id: "triceps-018",
      name: "Assisted Dip",
      group: "triceps",
      description: "Use the assisted dip machine to set your counterweight, grip the handles, and lower your body until your upper arms are parallel to the floor. Press back up to full lockout, squeezing your triceps at the top. Progressively reduce assistance as your strength improves.",
      videoId: "9llvBAV4RHI",
      svgKey: "dip-asistido",
    },
    {
      id: "triceps-019",
      name: "Skull Crusher",
      group: "triceps",
      description: "Lie flat on a bench holding an EZ bar or barbell with arms extended straight up. Lower the bar toward your forehead by bending only at the elbows, keeping your upper arms vertical. Press back up to full extension by contracting your triceps — this direct overhead load maximally stretches the long head.",
      videoId: "d_KZxkY_0cM",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-020",
      name: "EZ Bar Skull Crusher",
      group: "triceps",
      description: "Lie on a bench holding an EZ bar at the angled grip with arms extended upward. Lower the bar toward your forehead by bending at the elbows, then press back up. The angled EZ bar grip reduces wrist stress compared to a straight bar while delivering the same tricep stretch.",
      videoId: "ir5PsbniVSc",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-021",
      name: "Dumbbell Skull Crusher",
      group: "triceps",
      description: "Lie on a bench holding dumbbells with arms extended upward, palms facing each other. Lower both dumbbells toward your temples by bending at the elbows, then extend back to the start. Using dumbbells allows each arm to move independently, helping identify and correct strength imbalances.",
      videoId: "p9lVtxJISnk",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-022",
      name: "Dip",
      group: "triceps",
      description: "Grip parallel dip bars and keep your torso upright (vertical) to shift emphasis to the triceps rather than the chest. Lower yourself until your upper arms are parallel to the floor, then press back up to full lockout. Keep your elbows close to your sides throughout — flaring increases pec involvement.",
      videoId: "2z8JmcrW-As",
      svgKey: "dip-asistido",
    },
    {
      id: "triceps-023",
      name: "Bench Dip",
      group: "triceps",
      description: "Place your hands behind you on a bench with legs extended in front and heels on the floor. Lower your body by bending your elbows until your arms reach 90 degrees, then press back up to full extension. Keep your back close to the bench throughout — this triceps isolation exercise requires no equipment.",
      videoId: "0326dy_-CzM",
      svgKey: "dip-asistido",
    },
    {
      id: "triceps-024",
      name: "Single-Arm Overhead Cable Extension",
      group: "triceps",
      description: "Set a cable pulley high, face away from the machine, and hold the handle with one hand behind your head. Extend your forearm forward and upward to full lockout, then return slowly. The overhead position stretches the long head maximally — performing one arm at a time allows greater range of motion.",
      videoId: "sHB7pGnSOmE",
      svgKey: "extension-triceps-overhead",
    },
    {
      id: "triceps-025",
      name: "Rope Overhead Extension",
      group: "triceps",
      description: "Set a cable at the lowest position, face away from the machine, and hold the rope behind your head with both hands. Extend your forearms overhead to full lockout, separating the rope at the top. Return slowly — the rope allows natural wrist rotation and the cable maintains tension throughout the stretch.",
      videoId: "YbX7Wd8jQ-Q",
      svgKey: "extension-triceps-overhead",
    },
    {
      id: "triceps-026",
      name: "Diamond Push-Up",
      group: "triceps",
      description: "Form a diamond shape with your thumbs and index fingers and lower your chest toward your hands. Keep your elbows close to your sides throughout the movement. Press back up to full extension — the narrow hand position maximally loads the triceps by removing chest contribution.",
      videoId: "J0DXyMHj7YA",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-027",
      name: "Reverse-Grip Pushdown",
      group: "triceps",
      description: "Attach a straight bar to a high cable and grip it with an underhand (supinated) grip. Keeping your upper arms pinned to your sides, push the bar down to full elbow extension. Return slowly — the supinated grip shifts emphasis to the lateral head of the triceps and activates more total tricep fibers.",
      videoId: "hjN8OmB8OC0",
      svgKey: "pushdown-triceps",
    },
    {
      id: "triceps-028",
      name: "Single-Arm Pushdown",
      group: "triceps",
      description: "Attach a single handle to a high cable and grip it with one hand. Keep your upper arm pinned to your side and push the handle down to full elbow extension. Return with control — training one arm at a time allows you to identify and correct strength imbalances between sides.",
      videoId: "kiuVA0gs3EI",
      svgKey: "pushdown-triceps",
    },
    {
      id: "triceps-029",
      name: "JM Press",
      group: "triceps",
      description: "Lie on a bench holding a barbell with a shoulder-width grip. Lower the bar to just above your chin by bending your elbows outward and forward — it is a hybrid of a close-grip bench press and skull crusher. Press back up by extending your elbows — this compound movement is one of the most effective tricep mass builders.",
      videoId: "MrKnYFxKgMw",
      svgKey: "press-frances-maquina",
    },
    {
      id: "triceps-030",
      name: "Floor Press",
      group: "triceps",
      description: "Lie flat on the floor holding dumbbells or a barbell with arms extended. Lower until your upper arms rest on the floor, pause for a moment, then press back up to full extension. The floor limits range of motion at the bottom, eliminating the pec stretch and focusing the load entirely on the triceps.",
      videoId: "uUGDRwge4F8",
      svgKey: "press-frances-maquina",
    },
  ],

  shoulders: [
    {
      id: "shoulders-001",
      name: "Dumbbell Overhead Press",
      group: "shoulders",
      description: "Sit or stand holding dumbbells at shoulder height with palms facing forward. Press the dumbbells overhead to full arm extension, bringing them together slightly at the top. Lower with control back to shoulder height — avoid arching your lower back by bracing your core throughout.",
      videoId: "OLePvpxQEGk",
      svgKey: "press-militar-mancuernas",
    },
    {
      id: "shoulders-002",
      name: "Dumbbell Lateral Raise",
      group: "shoulders",
      description: "Stand holding dumbbells at your sides with a slight bend in your elbows. Raise the dumbbells out to your sides until your arms are parallel to the floor, leading with your elbows. Lower slowly — resist gravity on the way down for greater medial deltoid development.",
      videoId: "Kl3LEzQ5Zqs",
      svgKey: "elevacion-lateral",
    },
    {
      id: "shoulders-003",
      name: "Face Pull",
      group: "shoulders",
      description: "Attach a rope to a cable machine at face height. Pull the rope toward your face by driving your elbows back and outward, separating your hands as the rope reaches your forehead. This exercise directly targets the rear delts and external rotators — crucial for shoulder health and posture.",
      videoId: "IeOqdw9WI90",
      svgKey: "face-pull",
    },
    {
      id: "shoulders-004",
      name: "Dumbbell Front Raise",
      group: "shoulders",
      description: "Stand holding dumbbells in front of your thighs with palms facing down. Raise both dumbbells in front of you to shoulder height, keeping a slight elbow bend throughout. Lower slowly to the starting position — this isolates the anterior (front) head of the deltoid.",
      videoId: "yHx8wPv4RPo",
      svgKey: "elevacion-frontal",
    },
    {
      id: "shoulders-005",
      name: "Reverse Fly (Dumbbell)",
      group: "shoulders",
      description: "Hinge forward until your torso is nearly parallel to the floor, holding dumbbells below your chest with a slight elbow bend. Raise both arms out to your sides in a reverse fly motion until they reach shoulder height, squeezing your rear delts. Lower slowly — do not let momentum take over.",
      videoId: "xvEkgGUrGPM",
      svgKey: "pajaros-reversefly",
    },
    {
      id: "shoulders-006",
      name: "Arnold Press",
      group: "shoulders",
      description: "Start with dumbbells at shoulder height, palms facing you, elbows in front. As you press overhead, rotate your palms forward, finishing with thumbs facing back at full extension. Reverse the rotation as you lower — this rotation recruits all three heads of the deltoid through the full range.",
      videoId: "6K_N9AGhItQ",
      svgKey: "press-arnold",
    },
    {
      id: "shoulders-007",
      name: "Dumbbell Shrug",
      group: "shoulders",
      description: "Stand holding dumbbells at your sides with arms fully extended. Elevate your shoulders straight up toward your ears as high as possible, hold briefly at the top, then lower slowly. Do not roll your shoulders — the movement is purely vertical to isolate the upper trapezius.",
      videoId: "1OY7v02l2vA",
      svgKey: "encogimientos-hombros",
    },
    {
      id: "shoulders-008",
      name: "Machine Shoulder Press",
      group: "shoulders",
      description: "Sit in the shoulder press machine with handles at shoulder height and your back against the pad. Press the handles overhead to full extension, then lower with control. The machine's fixed path lets you focus on deltoid activation without balancing free weights.",
      videoId: "6v4nrRVySj0",
      svgKey: "press-hombro-maquina",
    },
    {
      id: "shoulders-009",
      name: "Machine Lateral Raise",
      group: "shoulders",
      description: "Sit in the lateral raise machine with pads against your upper arms just above the elbows. Raise your arms out to shoulder height against the resistance, squeezing your medial delts at the top. Lower slowly — the machine maintains constant tension throughout the range.",
      videoId: "Zi9nYtLsuz0",
      svgKey: "elevacion-lateral-maquina",
    },
    {
      id: "shoulders-010",
      name: "Reverse Pec Deck",
      group: "shoulders",
      description: "Sit facing the pec deck machine with your chest against the pad and grip the handles in front of you. Pull the handles out to your sides in a reverse fly motion, squeezing your rear delts at the end range. Return slowly — this machine provides constant tension and great rear delt isolation.",
      videoId: "7tgx6QHB0-A",
      svgKey: "reverse-pec-deck",
    },
    {
      id: "shoulders-011",
      name: "Smith Machine Shoulder Press",
      group: "shoulders",
      description: "Sit under a Smith machine bar set at shoulder height and grip slightly wider than shoulder-width. Press the bar overhead to full extension, then lower with control to shoulder height. The fixed bar path eliminates lateral stability demands, letting you focus purely on shoulder pressing strength.",
      videoId: "E7ngsffMPR0",
      svgKey: "smith-press-hombro",
    },
    {
      id: "shoulders-012",
      name: "Machine Shrug",
      group: "shoulders",
      description: "Stand or sit in the shrug machine, gripping the handles at your sides. Elevate your shoulders straight up toward your ears as high as possible, hold briefly, then lower with full control. The machine allows heavier loading than dumbbells, building upper trap mass effectively.",
      videoId: "NJ8U95vMtZg",
      svgKey: "maquina-encogimientos",
    },
    {
      id: "shoulders-013",
      name: "Seated Machine Shoulder Press",
      group: "shoulders",
      description: "Sit in the seated shoulder press machine adjusted to your torso height. Press the handles straight overhead to full lockout, then lower with control. This variation provides full back support for strict pressing, ideal for isolating the deltoids without lower back involvement.",
      videoId: "Nxwict54-Q0",
      svgKey: "press-sentado-maquina-hombro",
    },
    {
      id: "shoulders-014",
      name: "Cable Lateral Raise",
      group: "shoulders",
      description: "Set a cable at the lowest point, stand to one side, and grip the handle with the far hand. Raise your arm out to shoulder height, keeping a slight elbow bend and leading with your elbow. Lower slowly — cables maintain tension at the bottom of the range where dumbbells drop off.",
      videoId: "lMJUXEvcMkQ",
      svgKey: "elevacion-lateral-cable",
    },
    {
      id: "shoulders-015",
      name: "Cable Face Pull",
      group: "shoulders",
      description: "Attach a rope to a cable machine at face height. Pull the rope toward your face by driving your elbows back and outward, separating your hands as the rope reaches your forehead. Squeeze your rear delts and external rotators hard at the peak — this is a key shoulder health movement.",
      videoId: "cXn9j-Uah7k",
      svgKey: "face-pull-cable",
    },
    {
      id: "shoulders-016",
      name: "Band Front Raise",
      group: "shoulders",
      description: "Stand on a resistance band and hold the ends at thigh level with palms down. Raise both arms in front of you to shoulder height, keeping a slight elbow bend. Lower slowly — bands increase resistance as you raise higher, matching the strength curve of the anterior deltoid.",
      videoId: "pYVlZiu2Mps",
      svgKey: "elevacion-frontal-banda",
    },
    {
      id: "shoulders-017",
      name: "Band Shoulder Press",
      group: "shoulders",
      description: "Stand on a resistance band with feet shoulder-width apart and hold one end in each hand at shoulder height. Press both hands overhead to full extension, then lower with control. Bands add accommodating resistance — harder at lockout where you're strongest.",
      videoId: "1-VfJqjYquQ",
      svgKey: "press-banda-hombros",
    },
    {
      id: "shoulders-018",
      name: "Band Pull-Apart",
      group: "shoulders",
      description: "Hold a resistance band in front of you at shoulder height with both hands, arms extended and grip shoulder-width apart. Pull the band apart horizontally by driving both hands out to your sides until the band touches your chest. Squeeze your rear delts and return slowly — excellent for posture and shoulder health.",
      videoId: "osRimvxXlKQ",
      svgKey: "pull-apart-banda",
    },
    {
      id: "shoulders-019",
      name: "Barbell Overhead Press",
      group: "shoulders",
      description: "Stand holding a barbell at shoulder height with an overhand grip just outside shoulder-width. Press the bar overhead to full arm extension, moving your head slightly back to clear the bar, then forward again at lockout. Lower with control — this is the foundational compound movement for total shoulder development.",
      videoId: "2yjwXTZQDDI",
      svgKey: "press-militar-mancuernas",
    },
    {
      id: "shoulders-020",
      name: "Push Press",
      group: "shoulders",
      description: "Hold a barbell at shoulder height and initiate the press with a slight knee dip and leg drive. Use the upward momentum to help press the bar overhead to full extension, then lower with full control back to your shoulders. The leg drive allows heavier loads than a strict press, building overhead strength.",
      videoId: "X6MSaY4XPRA",
      svgKey: "press-militar-mancuernas",
    },
    {
      id: "shoulders-021",
      name: "Seated Dumbbell Press",
      group: "shoulders",
      description: "Sit on a bench with back support and hold dumbbells at shoulder height with palms facing forward. Press both dumbbells overhead to full extension, then lower with control back to shoulder height. The seated position removes leg drive and isolates the deltoids — ideal for strict shoulder strength.",
      videoId: "HzIiNhHhhtA",
      svgKey: "press-militar-mancuernas",
    },
    {
      id: "shoulders-022",
      name: "Cable Upright Row",
      group: "shoulders",
      description: "Stand at a cable machine with the pulley at the lowest setting and grip a straight bar or rope. Pull the bar straight up along your body to chin height by driving your elbows upward and outward. Lower with control — this movement targets the medial deltoids and upper traps simultaneously.",
      videoId: "XNxlMfqUNiM",
      svgKey: "elevacion-lateral-cable",
    },
    {
      id: "shoulders-023",
      name: "Barbell Upright Row",
      group: "shoulders",
      description: "Stand holding a barbell with an overhand grip slightly narrower than shoulder-width. Pull the bar straight up to chin height by driving your elbows high and out to the sides. Lower with control — keep elbows higher than wrists throughout the pull to maximize medial delt activation.",
      videoId: "MjOlwwfKPsw",
      svgKey: "elevacion-lateral",
    },
    {
      id: "shoulders-024",
      name: "Cable Rear Delt Fly",
      group: "shoulders",
      description: "Set two cables at head height and cross your arms to grab the opposite handles. Pull each cable outward and back in a reverse fly motion, squeezing your rear delts at full arm extension. Return slowly — the cable maintains constant tension throughout, unlike dumbbells which drop off at the bottom.",
      videoId: "rPdn2dKMV94",
      svgKey: "pajaros-reversefly",
    },
    {
      id: "shoulders-025",
      name: "Leaning Lateral Raise",
      group: "shoulders",
      description: "Hold a support (rack upright or cable) with one hand and lean outward so your body is at an angle. With the other hand, raise a dumbbell out to the side to shoulder height. The lean stretches the medial deltoid at the bottom and provides a greater range of motion than a standing raise.",
      videoId: "fk9g3SflETE",
      svgKey: "elevacion-lateral",
    },
    {
      id: "shoulders-026",
      name: "Seated Bent-Over Rear Delt Raise",
      group: "shoulders",
      description: "Sit on the edge of a bench and hinge forward until your torso is nearly parallel to the floor. Hold dumbbells hanging below your chest with a slight elbow bend and raise them out to the sides until your arms reach shoulder height. Lower slowly — the seated position removes momentum and forces strict rear delt isolation.",
      videoId: "0dT0akI0-Aw",
      svgKey: "pajaros-reversefly",
    },
    {
      id: "shoulders-027",
      name: "Plate Front Raise",
      group: "shoulders",
      description: "Hold a weight plate with both hands at the 3 and 9 o'clock positions, arms extended at hip level. Raise the plate straight in front of you to shoulder height, then lower with control. The plate creates a slightly different grip angle than dumbbells and challenges the anterior deltoid and serratus.",
      videoId: "fQOGWFOKKj8",
      svgKey: "elevacion-frontal",
    },
    {
      id: "shoulders-028",
      name: "Cable Front Raise",
      group: "shoulders",
      description: "Set a cable at the lowest pulley, grip the bar or handle with one or both hands, and stand facing away. Raise your arm(s) in front of you to shoulder height, then lower with control against cable tension. Cables provide constant tension at the bottom where dumbbells are easiest — a key advantage for front delt training.",
      videoId: "gkIDxYfKKcQ",
      svgKey: "elevacion-frontal-banda",
    },
    {
      id: "shoulders-029",
      name: "External Rotation (Band)",
      group: "shoulders",
      description: "Hold a resistance band with your elbow bent at 90 degrees and upper arm pinned to your side. Rotate your forearm outward against the band resistance, then return slowly. Perform all reps on one side before switching — external rotation directly trains the rotator cuff, essential for long-term shoulder health.",
      videoId: "Gp_RJeFhDaQ",
      svgKey: "rotacion-externa-banda",
    },
    {
      id: "shoulders-030",
      name: "Pike Push-Up",
      group: "shoulders",
      description: "Start in a downward-dog position with your hips high and arms and legs straight. Bend your elbows to lower the top of your head toward the floor, then press back up by extending your arms. This bodyweight movement targets the anterior and lateral deltoids — a useful shoulder press alternative requiring no equipment.",
      videoId: "x7_I5SUAd00",
      svgKey: "press-militar-mancuernas",
    },
  ],

  abs: [
    {
      id: "abs-001",
      name: "Plank",
      group: "abs",
      description: "Start in a push-up position but rest on your forearms instead of your hands. Keep your body in a straight line from head to heels by squeezing your core, glutes, and quads simultaneously. Hold for the target duration — do not let your hips sag or pike upward.",
      videoId: "v25dawSzRTM",
      svgKey: "plancha-banda",
    },
    {
      id: "abs-002",
      name: "Cable Crunch",
      group: "abs",
      description: "Kneel at a cable machine with the rope attachment at the high pulley. Hold the rope beside your head and crunch your elbows toward your knees by flexing your spine — not by pulling with your arms. The movement is entirely spinal flexion; your hips stay stationary throughout.",
      videoId: "dkGwcfo9zto",
      svgKey: "crunch-cable",
    },
    {
      id: "abs-003",
      name: "Hanging Leg Raise",
      group: "abs",
      description: "Hang from a pull-up bar with your arms fully extended and your body still. Raise your legs by flexing your hips and rounding your lower back slightly at the top — this posterior pelvic tilt ensures the abs do the work, not just the hip flexors. Lower slowly without swinging.",
      videoId: "2n4UqRIJyk4",
      svgKey: "elevacion-piernas-romana",
    },
    {
      id: "abs-004",
      name: "Dumbbell Crunch",
      group: "abs",
      description: "Lie on your back with knees bent and hold a dumbbell on your chest for resistance. Crunch your upper body toward your knees by flexing your spine, lifting your shoulder blades off the floor. Lower with control — do not pull on your neck and keep the movement short and focused.",
      videoId: "G9XfQJPBJVI",
      svgKey: "crunch-mancuerna",
    },
    {
      id: "abs-005",
      name: "Russian Twist",
      group: "abs",
      description: "Sit with knees bent and feet hovering above the floor, lean back until your torso forms roughly a 45-degree angle. Rotate your torso from side to side, touching the floor beside each hip. Hold a weight plate or dumbbell to increase difficulty — the rotational movement targets your obliques.",
      videoId: "aRUMRbl7KS4",
      svgKey: "russian-twist",
    },
    {
      id: "abs-006",
      name: "Plank Row",
      group: "abs",
      description: "Start in a push-up position with hands on dumbbells shoulder-width apart. Row one dumbbell up to your hip while stabilizing your body against rotation, then lower and repeat on the other side. The anti-rotation demand makes this one of the most effective compound core exercises.",
      videoId: "dFRNH1YigEk",
      svgKey: "plancha-remo",
    },
    {
      id: "abs-007",
      name: "Woodchop (Dumbbell)",
      group: "abs",
      description: "Stand holding a dumbbell with both hands above one shoulder. Rotate your torso and swing the dumbbell diagonally downward to the opposite hip in a chopping motion. Control the return — this rotational exercise develops oblique strength through a full diagonal range.",
      videoId: "YIU0U_B57rU",
      svgKey: "woodchop-mancuerna",
    },
    {
      id: "abs-008",
      name: "Farmer's Carry",
      group: "abs",
      description: "Hold heavy dumbbells or kettlebells at your sides and walk for a set distance or time. Keep your shoulders packed, chest tall, and core braced against the lateral pull of the weights. This loaded carry builds grip strength, core stability, and total-body conditioning simultaneously.",
      videoId: "z7E_YU9P1jU",
      svgKey: "farmers-carry",
    },
    {
      id: "abs-009",
      name: "Side Bend",
      group: "abs",
      description: "Stand holding a dumbbell in one hand at your side. Lean to that side by contracting your obliques, lowering the weight toward your knee, then return upright by contracting the obliques on the opposite side. Complete all reps on one side before switching.",
      videoId: "44DazvtgpGE",
      svgKey: "side-bend",
    },
    {
      id: "abs-010",
      name: "Machine Crunch",
      group: "abs",
      description: "Sit in the ab crunch machine and grip the handles above your head or at chest level. Crunch forward by flexing your spine, bringing your elbows toward your knees against the resistance. Return slowly — the machine allows heavier progressive overload than bodyweight crunches.",
      videoId: "7T0ZUEt1m8s",
      svgKey: "crunch-maquina",
    },
    {
      id: "abs-011",
      name: "Machine Torso Rotation",
      group: "abs",
      description: "Sit in the torso rotation machine with your hips fixed and grip the handles in front of you. Rotate your torso against the resistance as far as possible, then return to center. Perform all reps in one direction before switching — this isolates the obliques through pure rotation.",
      videoId: "tP3S7tAVXy8",
      svgKey: "rotacion-torso-maquina",
    },
    {
      id: "abs-012",
      name: "Ab Roller Machine",
      group: "abs",
      description: "Sit in the ab roller machine and grip the handles. Roll forward by extending your hips and spine, controlling the descent, then contract your abs hard to pull yourself back to the starting position. This movement trains the abs through a full range of motion under load.",
      videoId: "MinlHnG7j4k",
      svgKey: "ab-roller-maquina",
    },
    {
      id: "abs-013",
      name: "Reverse Hyperextension",
      group: "abs",
      description: "Lie face down on a hyperextension bench with your hips at the edge and legs hanging. Raise your legs behind you by contracting your glutes and lower back, then lower with control. This targets the posterior chain — glutes, hamstrings, and spinal erectors simultaneously.",
      videoId: "4oBIoWieJB8",
      svgKey: "hiperextension-inversa",
    },
    {
      id: "abs-014",
      name: "High Pulley Crunch",
      group: "abs",
      description: "Kneel at a cable machine with the pulley set high and hold the rope attachment behind your neck. Crunch your elbows toward the floor by flexing your spine, keeping your hips stationary. Return slowly to full extension — this is a loaded spinal flexion movement for maximum ab overload.",
      videoId: "JzaIPJ8GV_w",
      svgKey: "crunch-polea-alta",
    },
    {
      id: "abs-015",
      name: "Pallof Press",
      group: "abs",
      description: "Stand perpendicular to a cable machine with the pulley at chest height. Hold the handle at your chest with both hands, then press it straight out in front of you and hold for a count before returning. The anti-rotation demand of this exercise trains core stability, not spinal flexion.",
      videoId: "5aZ0IhJS8O8",
      svgKey: "pallof-press",
    },
    {
      id: "abs-016",
      name: "Cable Woodchop",
      group: "abs",
      description: "Set a cable at shoulder height on one side, grab the handle with both hands, and rotate your torso to pull it diagonally downward across your body. Control the return — the cable maintains constant tension through the full rotational range of the obliques.",
      videoId: "pAplQXk3dkU",
      svgKey: "woodchop-cable",
    },
    {
      id: "abs-017",
      name: "Band Anti-Rotation",
      group: "abs",
      description: "Anchor a resistance band at chest height and hold it with both hands extended in front of you, standing sideways to the anchor. Hold the position against the rotational pull for a set duration. This isometric core stability exercise builds anti-rotation strength crucial for all athletic movements.",
      videoId: "8vflPTMBQ_g",
      svgKey: "anti-rotacion-banda",
    },
    {
      id: "abs-018",
      name: "Dead Bug",
      group: "abs",
      description: "Lie on your back with arms pointing toward the ceiling and knees bent at 90 degrees. Simultaneously lower one arm overhead and extend the opposite leg, then return to start and alternate sides. Keep your lower back pressed into the floor throughout — this trains deep core stability and coordination.",
      videoId: "4XLEnwUr1d8",
      svgKey: "dead-bug-banda",
    },
    {
      id: "abs-019",
      name: "Hanging Knee Raise",
      group: "abs",
      description: "Hang from a pull-up bar and draw your knees up toward your chest by flexing your hips and rounding your lower back at the top. Lower with control without swinging. This is the regression of hanging leg raises — it reduces the lever arm and focuses on the lower abs while minimizing hip flexor dominance.",
      videoId: "ZjEqPX06I1U",
      svgKey: "elevacion-piernas-romana",
    },
    {
      id: "abs-020",
      name: "V-Up",
      group: "abs",
      description: "Lie flat on your back with arms extended overhead and legs straight. Simultaneously raise your legs and torso, reaching your hands toward your feet in a V shape. Lower with control — the simultaneous upper and lower crunch maximizes rectus abdominis activation through a full range of motion.",
      videoId: "iP2fjvG0g3w",
      svgKey: "crunch-mancuerna",
    },
    {
      id: "abs-021",
      name: "Bicycle Crunch",
      group: "abs",
      description: "Lie on your back with hands lightly behind your head and legs in the air at 90 degrees. Bring one elbow toward the opposite knee while extending the other leg, then rotate to the other side in a pedaling motion. Keep your lower back pressed to the floor — this is the most effective oblique exercise in EMG studies.",
      videoId: "1we3bh9uhqY",
      svgKey: "russian-twist",
    },
    {
      id: "abs-022",
      name: "Cable Oblique Crunch",
      group: "abs",
      description: "Set a cable at head height and kneel sideways to the machine with one hand holding the rope. Crunch laterally downward toward your hip by contracting your oblique, then return to the start. The cable provides constant resistance throughout the lateral flexion — superior to side bends for oblique overload.",
      videoId: "4V3-0JKRXLI",
      svgKey: "crunch-cable",
    },
    {
      id: "abs-023",
      name: "Weighted Sit-Up",
      group: "abs",
      description: "Lie on your back with knees bent and hold a weight plate on your chest. Curl your upper body all the way up until you are sitting upright, then lower with full control. Adding weight to the sit-up provides progressive overload for the abs — start light and increase the plate as you get stronger.",
      videoId: "jDwoBqPH0jk",
      svgKey: "crunch-mancuerna",
    },
    {
      id: "abs-024",
      name: "Decline Sit-Up",
      group: "abs",
      description: "Secure your feet on a decline bench and lie back. Curl all the way up to sitting position, then lower with control. The decline angle increases the range of motion and adds bodyweight resistance compared to a flat-bench sit-up — hold a plate to your chest for added difficulty.",
      videoId: "1fbU_MkV7NE",
      svgKey: "crunch-mancuerna",
    },
    {
      id: "abs-025",
      name: "Ab Wheel Rollout",
      group: "abs",
      description: "Kneel on the floor holding the ab wheel with both hands. Roll forward slowly by extending your hips and spine until your torso is nearly parallel to the floor, then pull back to the starting position by contracting your abs. Keep your core braced throughout — this is one of the most demanding ab exercises.",
      videoId: "kx-Q3cmpb3g",
      svgKey: "ab-roller-maquina",
    },
    {
      id: "abs-026",
      name: "Landmine Rotation",
      group: "abs",
      description: "Hold the loaded end of a barbell in a landmine with both hands at chest height, arms extended. Rotate your torso from side to side in a sweeping arc, letting your hips pivot naturally. Keep your arms relatively straight and generate the motion from your core — this full-range rotation develops oblique power.",
      videoId: "sKarOFQKqok",
      svgKey: "rotacion-torso-maquina",
    },
    {
      id: "abs-027",
      name: "Hollow Body Hold",
      group: "abs",
      description: "Lie on your back and simultaneously lift your legs and shoulders off the floor, arms extended overhead. Compress your lower back into the floor by drawing your navel to your spine. Hold this hollowed position for the target duration — this isometric exercise builds deep core stability critical for all athletic movements.",
      videoId: "LlDNef_Ztsc",
      svgKey: "plancha-banda",
    },
    {
      id: "abs-028",
      name: "L-Sit Hold",
      group: "abs",
      description: "Support yourself on parallel bars or the floor with arms extended and raise your legs to hip height, keeping them straight. Hold the L position by pressing down into the bars and bracing your abs hard. This requires significant hip flexor and core strength — build up time in small increments.",
      videoId: "IUZJoSMGcoo",
      svgKey: "elevacion-piernas-romana",
    },
    {
      id: "abs-029",
      name: "Toe Touch",
      group: "abs",
      description: "Lie flat on your back with legs raised straight up toward the ceiling. Reach both hands upward toward your feet by crunching your upper body, then lower with control. Keep the movement short and focused on spinal flexion — reaching your toes is the goal, but quality of contraction matters more than range.",
      videoId: "FOm_eXoMqfI",
      svgKey: "crunch-mancuerna",
    },
    {
      id: "abs-030",
      name: "Dragon Flag",
      group: "abs",
      description: "Lie on a bench and grip the bench behind your head. Drive your legs and hips straight up until only your shoulder blades remain on the bench. Lower your entire body as one rigid unit, resisting gravity with your core. Raise back up — this advanced exercise trains the entire anterior chain under extreme load.",
      videoId: "pvz7k5gO-DE",
      svgKey: "elevacion-piernas-romana",
    },
  ],

  legs: [
    {
      id: "legs-001",
      name: "Goblet Squat",
      group: "legs",
      description: "Hold a dumbbell or kettlebell at your chest with both hands. Descend into a squat, keeping your chest upright and knees tracking over your toes. Drive through your heels to return to standing — the counterbalance of the weight helps you sit deeper with an upright torso.",
      videoId: "lRYBbchqxtI",
      svgKey: "sentadilla-goblet",
    },
    {
      id: "legs-002",
      name: "Romanian Deadlift",
      group: "legs",
      description: "Stand holding a barbell at hip height with an overhand grip. Hinge at your hips while keeping your back flat, pushing your hips backward as the bar travels down your thighs to mid-shin level. Drive your hips forward to return to standing — feel the stretch in your hamstrings at the bottom.",
      videoId: "CBOhr6H7BEY",
      svgKey: "peso-muerto-rumano-mancuernas",
    },
    {
      id: "legs-003",
      name: "Leg Press",
      group: "legs",
      description: "Sit in the leg press machine with your feet shoulder-width apart on the platform. Lower the platform toward your chest until your thighs reach 90 degrees, then press back up to near-full extension — stop just short of locking out your knees. Keep your lower back flat against the pad throughout.",
      videoId: "EotSw18oR9w",
      svgKey: "prensa-piernas",
    },
    {
      id: "legs-004",
      name: "Walking Lunge",
      group: "legs",
      description: "Step forward with one leg and lower your back knee toward the floor in a controlled lunge. Drive through your front heel to step forward into the next rep on the opposite leg. Keep your torso upright and your front knee tracking over your toes throughout the movement.",
      videoId: "Pbmj6xPo-Hw",
      svgKey: "zancada-caminando",
    },
    {
      id: "legs-005",
      name: "Sumo Squat",
      group: "legs",
      description: "Stand with feet significantly wider than shoulder-width and toes pointed out at 45 degrees. Descend by pushing your knees out in line with your toes while sitting your hips straight down. Drive through your heels to return to standing — the wide stance shifts emphasis to the inner thighs and glutes.",
      videoId: "kjlfpqXnyL8",
      svgKey: "sentadilla-sumo",
    },
    {
      id: "legs-006",
      name: "Step-Up",
      group: "legs",
      description: "Stand facing a box or bench, step up with one foot and drive through that heel to bring your other foot up. Step back down with control and repeat on the same leg before switching. Hold dumbbells at your sides to add resistance — this unilateral movement corrects strength imbalances.",
      videoId: "S9uzCELLo_0",
      svgKey: "step-up",
    },
    {
      id: "legs-007",
      name: "Bulgarian Split Squat",
      group: "legs",
      description: "Place your rear foot on a bench behind you and hold dumbbells at your sides. Lower your front knee toward the floor until your front thigh is parallel, then drive through your front heel to return. This is one of the most effective single-leg exercises for glute and quad development.",
      videoId: "uODWo4YqbT8",
      svgKey: "sentadilla-bulgara",
    },
    {
      id: "legs-008",
      name: "Leg Extension",
      group: "legs",
      description: "Sit in the leg extension machine with the pad resting on your lower shins just above the ankle. Extend both legs to full lockout, squeezing your quads hard at the top, then lower with control. This isolation exercise directly targets the quadriceps through pure knee extension.",
      videoId: "w72YiHz15CA",
      svgKey: "extension-cuadriceps",
    },
    {
      id: "legs-009",
      name: "Leg Curl",
      group: "legs",
      description: "Lie face down on the leg curl machine with the pad resting just above your heels. Curl your heels toward your glutes by contracting your hamstrings, then lower with full control. This is the primary isolation exercise for the hamstrings — move through the full range without momentum.",
      videoId: "MAbThtU8Sis",
      svgKey: "curl-isquiotibiales",
    },
    {
      id: "legs-010",
      name: "Hack Squat",
      group: "legs",
      description: "Position yourself in the hack squat machine with your shoulders against the pads and feet on the platform. Lower with control until your thighs are parallel or below, then press back up without locking out. The machine-guided path allows for a deep squat with emphasis on the quads.",
      videoId: "g9i05umL5vc",
      svgKey: "hack-squat",
    },
    {
      id: "legs-011",
      name: "Hip Adduction Machine",
      group: "legs",
      description: "Sit in the adduction machine with pads on the inside of your thighs. Squeeze your thighs together against the resistance, then return slowly. This machine directly isolates the adductors (inner thigh muscles) — essential for hip stability and injury prevention.",
      videoId: "ktLkqP1upq0",
      svgKey: "aduccion-cadera",
    },
    {
      id: "legs-012",
      name: "Hip Abduction Machine",
      group: "legs",
      description: "Sit in the abduction machine with pads on the outside of your thighs. Push your thighs apart against the resistance, then return with control. This machine targets the gluteus medius and hip abductors — key muscles for knee alignment and lateral hip stability.",
      videoId: "01HilwRf8m8",
      svgKey: "abduccion-cadera",
    },
    {
      id: "legs-013",
      name: "Cable Glute Kickback",
      group: "legs",
      description: "Attach an ankle cuff to the low cable pulley and stand facing the machine. Kick your leg back and upward in a controlled arc, squeezing your glute at the top. Keep your torso upright and avoid rotating your hips — the movement should be purely hip extension.",
      videoId: "n-cgsNePyFo",
      svgKey: "patada-gluteo-polea",
    },
    {
      id: "legs-014",
      name: "Band Squat",
      group: "legs",
      description: "Stand on a resistance band with feet shoulder-width apart and hold the ends at shoulder height. Squat down by pushing your knees out and sitting your hips back, then drive through your heels to stand. The band provides accommodating resistance — hardest at the top where you're strongest.",
      videoId: "6rE0IYlMPZA",
      svgKey: "sentadilla-banda",
    },
    {
      id: "legs-015",
      name: "Band Romanian Deadlift",
      group: "legs",
      description: "Stand on a resistance band and hold the ends at hip height. Hinge at your hips while keeping your back flat, pushing your hips back as the bands lower toward your mid-shin. Drive your hips forward to return to standing, feeling the hamstring stretch at the bottom.",
      videoId: "jaRAR9l1e2o",
      svgKey: "peso-muerto-banda",
    },
    {
      id: "legs-016",
      name: "Clamshell",
      group: "legs",
      description: "Lie on your side with a resistance band just above your knees, hips stacked, and knees bent at 90 degrees. Rotate your top knee upward like a clamshell opening while keeping your feet together and hips from rolling back. Return slowly — this targets the gluteus medius for hip abduction strength.",
      videoId: "TT__6i6hS5w",
      svgKey: "clamshell-banda",
    },
    {
      id: "legs-017",
      name: "Glute Bridge",
      group: "legs",
      description: "Lie on your back with knees bent and a resistance band across your hips. Drive your hips upward by squeezing your glutes, pushing your knees outward against the band at the top. Hold for a moment at full hip extension, then lower with control.",
      videoId: "OUgsJ8-Vi0E",
      svgKey: "puente-gluteos-banda",
    },
    {
      id: "legs-018",
      name: "Monster Walk",
      group: "legs",
      description: "Place a resistance band around your ankles and stand in a half-squat position. Step laterally in a wide stride, keeping tension in the band throughout and maintaining the squat depth. Walk in one direction for a set number of steps, then return — this builds glute medius and hip abductor endurance.",
      videoId: "TeyfkdXAgUg",
      svgKey: "monster-walk",
    },
    {
      id: "legs-019",
      name: "Barbell Back Squat",
      group: "legs",
      description: "Position a barbell on your upper traps, stand with feet shoulder-width apart and toes slightly out. Descend by pushing your knees out and sitting your hips back until your thighs are parallel. Drive through your heels to stand — this compound movement is the most effective exercise for overall leg development.",
      videoId: "SW_C1A-rejs",
      svgKey: "sentadilla-goblet",
    },
    {
      id: "legs-020",
      name: "Front Squat",
      group: "legs",
      description: "Hold a barbell in the front rack position on your front deltoids, elbows high. Descend into a deep squat keeping your torso completely upright, knees tracking over your toes. Drive upward through your heels — the front rack position forces a more vertical torso and shifts emphasis to the quads.",
      videoId: "uYumuL_G_V0",
      svgKey: "sentadilla-goblet",
    },
    {
      id: "legs-021",
      name: "Smith Machine Squat",
      group: "legs",
      description: "Set a Smith machine bar at shoulder height, position it on your upper traps, and stand with feet slightly forward of the bar. Descend to parallel, then press back up. The fixed vertical path allows you to focus on quad activation and is useful for training through mild knee or back discomfort.",
      videoId: "WZIS66l1WV8",
      svgKey: "hack-squat",
    },
    {
      id: "legs-022",
      name: "Dumbbell Romanian Deadlift",
      group: "legs",
      description: "Stand holding dumbbells in front of your thighs with a neutral grip. Hinge at your hips, pushing them back while keeping your back flat and dumbbells close to your legs. Lower until you feel a strong hamstring stretch at mid-shin level, then drive your hips forward to stand.",
      videoId: "hCDzSR6bW10",
      svgKey: "peso-muerto-rumano-mancuernas",
    },
    {
      id: "legs-023",
      name: "Single-Leg Leg Press",
      group: "legs",
      description: "Sit in the leg press machine and position one foot at the center of the platform. Lower the platform with control until your knee is at 90 degrees, then press back up without fully locking out. Unilateral training corrects muscle imbalances and increases quad and glute activation per leg.",
      videoId: "IiJZHmYKXOE",
      svgKey: "prensa-piernas",
    },
    {
      id: "legs-024",
      name: "Seated Leg Curl",
      group: "legs",
      description: "Sit in the seated leg curl machine with the pad resting just above your heels and back against the support. Curl your heels toward your glutes by contracting your hamstrings, then lower with full control. The seated position changes the hip angle versus the prone curl, increasing tension on the upper hamstring.",
      videoId: "1Tq3QdYUuHs",
      svgKey: "curl-isquiotibiales",
    },
    {
      id: "legs-025",
      name: "Nordic Hamstring Curl",
      group: "legs",
      description: "Kneel on a pad with your ankles secured under a bar or pad. Lower your torso toward the floor as slowly as possible by resisting with your hamstrings, then use your hands to push up and return. This eccentric-dominant exercise is one of the most effective hamstring strengthening methods for injury prevention.",
      videoId: "Gf6HQj3jBj0",
      svgKey: "curl-isquiotibiales",
    },
    {
      id: "legs-026",
      name: "Reverse Lunge",
      group: "legs",
      description: "Stand holding dumbbells and step one foot backward, lowering your rear knee toward the floor. Drive through your front heel to return to standing, then repeat on the other side. Stepping backward reduces shear force on the knee compared to a forward lunge, making it more knee-friendly.",
      videoId: "QOVaHwm-Q6U",
      svgKey: "zancada-caminando",
    },
    {
      id: "legs-027",
      name: "Lateral Lunge",
      group: "legs",
      description: "Stand with feet together, step widely to one side, and sit into that hip while keeping the other leg straight. Push off through the bent knee to return to standing. Lateral lunges target the adductors and gluteus medius — muscles often neglected by sagittal-plane-only training.",
      videoId: "gwWv7aPcD88",
      svgKey: "zancada-caminando",
    },
    {
      id: "legs-028",
      name: "Single-Leg Romanian Deadlift",
      group: "legs",
      description: "Stand on one leg holding a dumbbell in the opposite hand. Hinge at the hip, extending the free leg behind you as your torso drops, lowering the dumbbell toward your standing foot. Return to standing by driving your hip forward — this unilateral hinge develops hamstring strength and balance simultaneously.",
      videoId: "2Y64bL8x0ak",
      svgKey: "peso-muerto-rumano-mancuernas",
    },
    {
      id: "legs-029",
      name: "Barbell Hip Thrust",
      group: "legs",
      description: "Sit with your upper back against a bench and a padded barbell across your hips. Drive through your heels to thrust your hips upward until your thighs are parallel to the floor, squeezing your glutes hard at the top. Lower with control — the hip thrust is the most effective exercise for gluteus maximus activation.",
      videoId: "LM8XHLYJoYs",
      svgKey: "puente-gluteos-banda",
    },
    {
      id: "legs-030",
      name: "Box Jump",
      group: "legs",
      description: "Stand facing a sturdy box at a comfortable height. Bend your knees and swing your arms, then jump explosively onto the box, landing softly in a quarter-squat position. Step back down carefully and reset. This plyometric movement develops explosive power and trains the fast-twitch fibers of the quads and glutes.",
      videoId: "52r_Ul5k03g",
      svgKey: "step-up",
    },
  ],

};
